linters-settings:
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - performance
      - style
  gofumpt:
    lang-version: 1.20

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - varcheck
    - misspell
    - lll
    - gofumpt

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "Error return value is not checked"

run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"
