version: "3"
services:
  go:
    build:
      context: ../
      dockerfile: ./remote-dev/Dockerfile
    env_file:
      - .env
    tty: true
    ports:
      - ${GO_PORT}:${GO_PORT}
      - ${GO_TLS_PORT}:${GO_TLS_PORT}
      - ${GO_DEBUG_PORT}:${GO_DEBUG_PORT}
      - ${REMOTE_CONTAINER_PORT}:${REMOTE_CONTAINER_PORT}
    volumes:
      - ../:/data
      - /data/ide
      - ~/.gitconfig:/home/go/.gitconfig
      - ../cert/${SECRET_KEY_FILE_NAME}:${SECRET_KEY_PATH}/${SECRET_KEY_FILE_NAME}
      - ../cert/${CERT_FILE_NAME}:${CERT_PATH}/${CERT_FILE_NAME}
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../.devcontainer/infra/mysql/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: "redis:latest"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - "redis-data:/data"

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - ${REDIS_DEBUG_GUI_PORT}:8001
    volumes:
      - "redisinsight-data:/db"

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
  redisinsight-data:
    driver: local