version: "3"
services:
  go:
    build:
      context: ../
      dockerfile: ./goland-remote-dev/Dockerfile
    env_file:
      - .env
    tty: true
    ports:
      - ${GO_PORT}:${GO_PORT}
      - ${GO_DEBUG_PORT}:${GO_DEBUG_PORT}
      - "5994:5994"
    volumes:
      - ../:/data
      - /data/ide
      - ~/.gitconfig:/home/go/.gitconfig
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mysql
    environment:
      GO_PORT: ${GO_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../.devcontainer/infra/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}