version: "3"
services:
  go:
    build: ./infra/go/
    tty: true
    ports:
      - ${GO_PORT}:${GO_PORT}
      - ${GO_DEBUG_PORT}:${GO_DEBUG_PORT}
    volumes:
      - ${PROJECT_ROOT}:/data
    security_opt: # delve用に必要
      - apparmor:unconfined
    cap_add: # delve用に必要
      - SYS_PTRACE
    environment:
      FRONT_DOMAIN: ${FRONT_DOMAIN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GO_PORT: ${GO_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${PROJECT_ROOT}/.devcontainer/infra/mysql/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  db-data:
    driver: local