name: Go CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_TEST_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ^1.22

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"${{ secrets.DB_HOST }}" -P"${{ secrets.DB_PORT }}" --silent; do
            echo 'waiting for mysql'
            sleep 1
          done

      - name: Execute SQL script
        run: |
          mysql -h ${{ secrets.DB_HOST }} --port ${{ secrets.DB_PORT }} -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "$(cat ./.devcontainer/infra/mysql/1_ddl.sql)"

      - name: Run Test
        run: go test -p=1 ./...
